# Generated by Django 5.2.1 on 2025-06-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0002_tarea_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
    ]
